language: python
python:
        - "3.6"
cache:
        - pip
install:
        - pip install -r requirements.txt
script:
        - pytest -v --pep8 --cov
services:
        - mysql
before_install:
        - mysql -u root --password="" < testing/travis.sql
